//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontTA.SisProgWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alumno.services.sis.edu.pe/", ConfigurationName="SisProgWS.FamiliaWS")]
    public interface FamiliaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/buscarFamiliaRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/buscarFamiliaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.buscarFamiliaResponse buscarFamilia(FrontTA.SisProgWS.buscarFamiliaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/buscarFamiliaRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/buscarFamiliaResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.buscarFamiliaResponse> buscarFamiliaAsync(FrontTA.SisProgWS.buscarFamiliaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/eliminarFamiliaPorIdRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/eliminarFamiliaPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.eliminarFamiliaPorIdResponse eliminarFamiliaPorId(FrontTA.SisProgWS.eliminarFamiliaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/eliminarFamiliaPorIdRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/eliminarFamiliaPorIdResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.eliminarFamiliaPorIdResponse> eliminarFamiliaPorIdAsync(FrontTA.SisProgWS.eliminarFamiliaPorIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/insertarFamiliaRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/insertarFamiliaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.insertarFamiliaResponse insertarFamilia(FrontTA.SisProgWS.insertarFamiliaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/insertarFamiliaRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/insertarFamiliaResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.insertarFamiliaResponse> insertarFamiliaAsync(FrontTA.SisProgWS.insertarFamiliaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/modificarFamiliaRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/modificarFamiliaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.modificarFamiliaResponse modificarFamilia(FrontTA.SisProgWS.modificarFamiliaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/modificarFamiliaRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/modificarFamiliaResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.modificarFamiliaResponse> modificarFamiliaAsync(FrontTA.SisProgWS.modificarFamiliaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/listarFamiliasTodasRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/listarFamiliasTodasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.listarFamiliasTodasResponse listarFamiliasTodas(FrontTA.SisProgWS.listarFamiliasTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/listarFamiliasTodasRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/listarFamiliasTodasResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.listarFamiliasTodasResponse> listarFamiliasTodasAsync(FrontTA.SisProgWS.listarFamiliasTodasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/ObtenerHijosRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/ObtenerHijosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.ObtenerHijosResponse ObtenerHijos(FrontTA.SisProgWS.ObtenerHijosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/ObtenerHijosRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/ObtenerHijosResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.ObtenerHijosResponse> ObtenerHijosAsync(FrontTA.SisProgWS.ObtenerHijosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/obtenerFamiliaPorIdRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/obtenerFamiliaPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.obtenerFamiliaPorIdResponse obtenerFamiliaPorId(FrontTA.SisProgWS.obtenerFamiliaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/FamiliaWS/obtenerFamiliaPorIdRequest", ReplyAction="http://alumno.services.sis.edu.pe/FamiliaWS/obtenerFamiliaPorIdResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.obtenerFamiliaPorIdResponse> obtenerFamiliaPorIdAsync(FrontTA.SisProgWS.obtenerFamiliaPorIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alumno.services.sis.edu.pe/")]
    public partial class familia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellido_maternoField;
        
        private string apellido_paternoField;
        
        private string correo_electronicoField;
        
        private string direccionField;
        
        private int familia_idField;
        
        private string numero_telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido_materno {
            get {
                return this.apellido_maternoField;
            }
            set {
                this.apellido_maternoField = value;
                this.RaisePropertyChanged("apellido_materno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellido_paterno {
            get {
                return this.apellido_paternoField;
            }
            set {
                this.apellido_paternoField = value;
                this.RaisePropertyChanged("apellido_paterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo_electronico {
            get {
                return this.correo_electronicoField;
            }
            set {
                this.correo_electronicoField = value;
                this.RaisePropertyChanged("correo_electronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int familia_id {
            get {
                return this.familia_idField;
            }
            set {
                this.familia_idField = value;
                this.RaisePropertyChanged("familia_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numero_telefono {
            get {
                return this.numero_telefonoField;
            }
            set {
                this.numero_telefonoField = value;
                this.RaisePropertyChanged("numero_telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alumno.services.sis.edu.pe/")]
    public partial class alumno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int alumno_idField;
        
        private int dniField;
        
        private System.DateTime fecha_ingresoField;
        
        private bool fecha_ingresoFieldSpecified;
        
        private System.DateTime fecha_nacimientoField;
        
        private bool fecha_nacimientoFieldSpecified;
        
        private string nombreField;
        
        private string observacionesField;
        
        private familia padresField;
        
        private double pension_baseField;
        
        private string religionField;
        
        private ushort sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int alumno_id {
            get {
                return this.alumno_idField;
            }
            set {
                this.alumno_idField = value;
                this.RaisePropertyChanged("alumno_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha_ingreso {
            get {
                return this.fecha_ingresoField;
            }
            set {
                this.fecha_ingresoField = value;
                this.RaisePropertyChanged("fecha_ingreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_ingresoSpecified {
            get {
                return this.fecha_ingresoFieldSpecified;
            }
            set {
                this.fecha_ingresoFieldSpecified = value;
                this.RaisePropertyChanged("fecha_ingresoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha_nacimiento {
            get {
                return this.fecha_nacimientoField;
            }
            set {
                this.fecha_nacimientoField = value;
                this.RaisePropertyChanged("fecha_nacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_nacimientoSpecified {
            get {
                return this.fecha_nacimientoFieldSpecified;
            }
            set {
                this.fecha_nacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fecha_nacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("observaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public familia padres {
            get {
                return this.padresField;
            }
            set {
                this.padresField = value;
                this.RaisePropertyChanged("padres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double pension_base {
            get {
                return this.pension_baseField;
            }
            set {
                this.pension_baseField = value;
                this.RaisePropertyChanged("pension_base");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
                this.RaisePropertyChanged("religion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarFamilia", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class buscarFamiliaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellido_paterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellido_materno;
        
        public buscarFamiliaRequest() {
        }
        
        public buscarFamiliaRequest(string apellido_paterno, string apellido_materno) {
            this.apellido_paterno = apellido_paterno;
            this.apellido_materno = apellido_materno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarFamiliaResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class buscarFamiliaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontTA.SisProgWS.familia @return;
        
        public buscarFamiliaResponse() {
        }
        
        public buscarFamiliaResponse(FrontTA.SisProgWS.familia @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarFamiliaPorId", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class eliminarFamiliaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFamilia;
        
        public eliminarFamiliaPorIdRequest() {
        }
        
        public eliminarFamiliaPorIdRequest(int idFamilia) {
            this.idFamilia = idFamilia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarFamiliaPorIdResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class eliminarFamiliaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarFamiliaPorIdResponse() {
        }
        
        public eliminarFamiliaPorIdResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarFamilia", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class insertarFamiliaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontTA.SisProgWS.familia familia;
        
        public insertarFamiliaRequest() {
        }
        
        public insertarFamiliaRequest(FrontTA.SisProgWS.familia familia) {
            this.familia = familia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarFamiliaResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class insertarFamiliaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarFamiliaResponse() {
        }
        
        public insertarFamiliaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarFamilia", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class modificarFamiliaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontTA.SisProgWS.familia familia;
        
        public modificarFamiliaRequest() {
        }
        
        public modificarFamiliaRequest(FrontTA.SisProgWS.familia familia) {
            this.familia = familia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarFamiliaResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class modificarFamiliaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarFamiliaResponse() {
        }
        
        public modificarFamiliaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarFamiliasTodas", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class listarFamiliasTodasRequest {
        
        public listarFamiliasTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarFamiliasTodasResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class listarFamiliasTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontTA.SisProgWS.familia[] @return;
        
        public listarFamiliasTodasResponse() {
        }
        
        public listarFamiliasTodasResponse(FrontTA.SisProgWS.familia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerHijos", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class ObtenerHijosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFamilia;
        
        public ObtenerHijosRequest() {
        }
        
        public ObtenerHijosRequest(int idFamilia) {
            this.idFamilia = idFamilia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerHijosResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class ObtenerHijosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontTA.SisProgWS.alumno[] @return;
        
        public ObtenerHijosResponse() {
        }
        
        public ObtenerHijosResponse(FrontTA.SisProgWS.alumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerFamiliaPorId", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class obtenerFamiliaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFamilia;
        
        public obtenerFamiliaPorIdRequest() {
        }
        
        public obtenerFamiliaPorIdRequest(int idFamilia) {
            this.idFamilia = idFamilia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerFamiliaPorIdResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class obtenerFamiliaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontTA.SisProgWS.familia @return;
        
        public obtenerFamiliaPorIdResponse() {
        }
        
        public obtenerFamiliaPorIdResponse(FrontTA.SisProgWS.familia @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FamiliaWSChannel : FrontTA.SisProgWS.FamiliaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FamiliaWSClient : System.ServiceModel.ClientBase<FrontTA.SisProgWS.FamiliaWS>, FrontTA.SisProgWS.FamiliaWS {
        
        public FamiliaWSClient() {
        }
        
        public FamiliaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FamiliaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FamiliaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FamiliaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.buscarFamiliaResponse FrontTA.SisProgWS.FamiliaWS.buscarFamilia(FrontTA.SisProgWS.buscarFamiliaRequest request) {
            return base.Channel.buscarFamilia(request);
        }
        
        public FrontTA.SisProgWS.familia buscarFamilia(string apellido_paterno, string apellido_materno) {
            FrontTA.SisProgWS.buscarFamiliaRequest inValue = new FrontTA.SisProgWS.buscarFamiliaRequest();
            inValue.apellido_paterno = apellido_paterno;
            inValue.apellido_materno = apellido_materno;
            FrontTA.SisProgWS.buscarFamiliaResponse retVal = ((FrontTA.SisProgWS.FamiliaWS)(this)).buscarFamilia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.buscarFamiliaResponse> FrontTA.SisProgWS.FamiliaWS.buscarFamiliaAsync(FrontTA.SisProgWS.buscarFamiliaRequest request) {
            return base.Channel.buscarFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.buscarFamiliaResponse> buscarFamiliaAsync(string apellido_paterno, string apellido_materno) {
            FrontTA.SisProgWS.buscarFamiliaRequest inValue = new FrontTA.SisProgWS.buscarFamiliaRequest();
            inValue.apellido_paterno = apellido_paterno;
            inValue.apellido_materno = apellido_materno;
            return ((FrontTA.SisProgWS.FamiliaWS)(this)).buscarFamiliaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.eliminarFamiliaPorIdResponse FrontTA.SisProgWS.FamiliaWS.eliminarFamiliaPorId(FrontTA.SisProgWS.eliminarFamiliaPorIdRequest request) {
            return base.Channel.eliminarFamiliaPorId(request);
        }
        
        public int eliminarFamiliaPorId(int idFamilia) {
            FrontTA.SisProgWS.eliminarFamiliaPorIdRequest inValue = new FrontTA.SisProgWS.eliminarFamiliaPorIdRequest();
            inValue.idFamilia = idFamilia;
            FrontTA.SisProgWS.eliminarFamiliaPorIdResponse retVal = ((FrontTA.SisProgWS.FamiliaWS)(this)).eliminarFamiliaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.eliminarFamiliaPorIdResponse> FrontTA.SisProgWS.FamiliaWS.eliminarFamiliaPorIdAsync(FrontTA.SisProgWS.eliminarFamiliaPorIdRequest request) {
            return base.Channel.eliminarFamiliaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.eliminarFamiliaPorIdResponse> eliminarFamiliaPorIdAsync(int idFamilia) {
            FrontTA.SisProgWS.eliminarFamiliaPorIdRequest inValue = new FrontTA.SisProgWS.eliminarFamiliaPorIdRequest();
            inValue.idFamilia = idFamilia;
            return ((FrontTA.SisProgWS.FamiliaWS)(this)).eliminarFamiliaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.insertarFamiliaResponse FrontTA.SisProgWS.FamiliaWS.insertarFamilia(FrontTA.SisProgWS.insertarFamiliaRequest request) {
            return base.Channel.insertarFamilia(request);
        }
        
        public int insertarFamilia(FrontTA.SisProgWS.familia familia) {
            FrontTA.SisProgWS.insertarFamiliaRequest inValue = new FrontTA.SisProgWS.insertarFamiliaRequest();
            inValue.familia = familia;
            FrontTA.SisProgWS.insertarFamiliaResponse retVal = ((FrontTA.SisProgWS.FamiliaWS)(this)).insertarFamilia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.insertarFamiliaResponse> FrontTA.SisProgWS.FamiliaWS.insertarFamiliaAsync(FrontTA.SisProgWS.insertarFamiliaRequest request) {
            return base.Channel.insertarFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.insertarFamiliaResponse> insertarFamiliaAsync(FrontTA.SisProgWS.familia familia) {
            FrontTA.SisProgWS.insertarFamiliaRequest inValue = new FrontTA.SisProgWS.insertarFamiliaRequest();
            inValue.familia = familia;
            return ((FrontTA.SisProgWS.FamiliaWS)(this)).insertarFamiliaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.modificarFamiliaResponse FrontTA.SisProgWS.FamiliaWS.modificarFamilia(FrontTA.SisProgWS.modificarFamiliaRequest request) {
            return base.Channel.modificarFamilia(request);
        }
        
        public int modificarFamilia(FrontTA.SisProgWS.familia familia) {
            FrontTA.SisProgWS.modificarFamiliaRequest inValue = new FrontTA.SisProgWS.modificarFamiliaRequest();
            inValue.familia = familia;
            FrontTA.SisProgWS.modificarFamiliaResponse retVal = ((FrontTA.SisProgWS.FamiliaWS)(this)).modificarFamilia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.modificarFamiliaResponse> FrontTA.SisProgWS.FamiliaWS.modificarFamiliaAsync(FrontTA.SisProgWS.modificarFamiliaRequest request) {
            return base.Channel.modificarFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.modificarFamiliaResponse> modificarFamiliaAsync(FrontTA.SisProgWS.familia familia) {
            FrontTA.SisProgWS.modificarFamiliaRequest inValue = new FrontTA.SisProgWS.modificarFamiliaRequest();
            inValue.familia = familia;
            return ((FrontTA.SisProgWS.FamiliaWS)(this)).modificarFamiliaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.listarFamiliasTodasResponse FrontTA.SisProgWS.FamiliaWS.listarFamiliasTodas(FrontTA.SisProgWS.listarFamiliasTodasRequest request) {
            return base.Channel.listarFamiliasTodas(request);
        }
        
        public FrontTA.SisProgWS.familia[] listarFamiliasTodas() {
            FrontTA.SisProgWS.listarFamiliasTodasRequest inValue = new FrontTA.SisProgWS.listarFamiliasTodasRequest();
            FrontTA.SisProgWS.listarFamiliasTodasResponse retVal = ((FrontTA.SisProgWS.FamiliaWS)(this)).listarFamiliasTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.listarFamiliasTodasResponse> FrontTA.SisProgWS.FamiliaWS.listarFamiliasTodasAsync(FrontTA.SisProgWS.listarFamiliasTodasRequest request) {
            return base.Channel.listarFamiliasTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.listarFamiliasTodasResponse> listarFamiliasTodasAsync() {
            FrontTA.SisProgWS.listarFamiliasTodasRequest inValue = new FrontTA.SisProgWS.listarFamiliasTodasRequest();
            return ((FrontTA.SisProgWS.FamiliaWS)(this)).listarFamiliasTodasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.ObtenerHijosResponse FrontTA.SisProgWS.FamiliaWS.ObtenerHijos(FrontTA.SisProgWS.ObtenerHijosRequest request) {
            return base.Channel.ObtenerHijos(request);
        }
        
        public FrontTA.SisProgWS.alumno[] ObtenerHijos(int idFamilia) {
            FrontTA.SisProgWS.ObtenerHijosRequest inValue = new FrontTA.SisProgWS.ObtenerHijosRequest();
            inValue.idFamilia = idFamilia;
            FrontTA.SisProgWS.ObtenerHijosResponse retVal = ((FrontTA.SisProgWS.FamiliaWS)(this)).ObtenerHijos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.ObtenerHijosResponse> FrontTA.SisProgWS.FamiliaWS.ObtenerHijosAsync(FrontTA.SisProgWS.ObtenerHijosRequest request) {
            return base.Channel.ObtenerHijosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.ObtenerHijosResponse> ObtenerHijosAsync(int idFamilia) {
            FrontTA.SisProgWS.ObtenerHijosRequest inValue = new FrontTA.SisProgWS.ObtenerHijosRequest();
            inValue.idFamilia = idFamilia;
            return ((FrontTA.SisProgWS.FamiliaWS)(this)).ObtenerHijosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.obtenerFamiliaPorIdResponse FrontTA.SisProgWS.FamiliaWS.obtenerFamiliaPorId(FrontTA.SisProgWS.obtenerFamiliaPorIdRequest request) {
            return base.Channel.obtenerFamiliaPorId(request);
        }
        
        public FrontTA.SisProgWS.familia obtenerFamiliaPorId(int idFamilia) {
            FrontTA.SisProgWS.obtenerFamiliaPorIdRequest inValue = new FrontTA.SisProgWS.obtenerFamiliaPorIdRequest();
            inValue.idFamilia = idFamilia;
            FrontTA.SisProgWS.obtenerFamiliaPorIdResponse retVal = ((FrontTA.SisProgWS.FamiliaWS)(this)).obtenerFamiliaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.obtenerFamiliaPorIdResponse> FrontTA.SisProgWS.FamiliaWS.obtenerFamiliaPorIdAsync(FrontTA.SisProgWS.obtenerFamiliaPorIdRequest request) {
            return base.Channel.obtenerFamiliaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.obtenerFamiliaPorIdResponse> obtenerFamiliaPorIdAsync(int idFamilia) {
            FrontTA.SisProgWS.obtenerFamiliaPorIdRequest inValue = new FrontTA.SisProgWS.obtenerFamiliaPorIdRequest();
            inValue.idFamilia = idFamilia;
            return ((FrontTA.SisProgWS.FamiliaWS)(this)).obtenerFamiliaPorIdAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alumno.services.sis.edu.pe/", ConfigurationName="SisProgWS.AlumnoWS")]
    public interface AlumnoWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/AlumnoWS/insertarAlumnoRequest", ReplyAction="http://alumno.services.sis.edu.pe/AlumnoWS/insertarAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.insertarAlumnoResponse insertarAlumno(FrontTA.SisProgWS.insertarAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/AlumnoWS/insertarAlumnoRequest", ReplyAction="http://alumno.services.sis.edu.pe/AlumnoWS/insertarAlumnoResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.insertarAlumnoResponse> insertarAlumnoAsync(FrontTA.SisProgWS.insertarAlumnoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/AlumnoWS/eliminarAlumnoPorIdRequest", ReplyAction="http://alumno.services.sis.edu.pe/AlumnoWS/eliminarAlumnoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.eliminarAlumnoPorIdResponse eliminarAlumnoPorId(FrontTA.SisProgWS.eliminarAlumnoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/AlumnoWS/eliminarAlumnoPorIdRequest", ReplyAction="http://alumno.services.sis.edu.pe/AlumnoWS/eliminarAlumnoPorIdResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.eliminarAlumnoPorIdResponse> eliminarAlumnoPorIdAsync(FrontTA.SisProgWS.eliminarAlumnoPorIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/AlumnoWS/obtenerAlumnoPorIdRequest", ReplyAction="http://alumno.services.sis.edu.pe/AlumnoWS/obtenerAlumnoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.obtenerAlumnoPorIdResponse obtenerAlumnoPorId(FrontTA.SisProgWS.obtenerAlumnoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/AlumnoWS/obtenerAlumnoPorIdRequest", ReplyAction="http://alumno.services.sis.edu.pe/AlumnoWS/obtenerAlumnoPorIdResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.obtenerAlumnoPorIdResponse> obtenerAlumnoPorIdAsync(FrontTA.SisProgWS.obtenerAlumnoPorIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/AlumnoWS/listarAlumnosTodosRequest", ReplyAction="http://alumno.services.sis.edu.pe/AlumnoWS/listarAlumnosTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.listarAlumnosTodosResponse listarAlumnosTodos(FrontTA.SisProgWS.listarAlumnosTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/AlumnoWS/listarAlumnosTodosRequest", ReplyAction="http://alumno.services.sis.edu.pe/AlumnoWS/listarAlumnosTodosResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.listarAlumnosTodosResponse> listarAlumnosTodosAsync(FrontTA.SisProgWS.listarAlumnosTodosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/AlumnoWS/modificarAlumnoRequest", ReplyAction="http://alumno.services.sis.edu.pe/AlumnoWS/modificarAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontTA.SisProgWS.modificarAlumnoResponse modificarAlumno(FrontTA.SisProgWS.modificarAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alumno.services.sis.edu.pe/AlumnoWS/modificarAlumnoRequest", ReplyAction="http://alumno.services.sis.edu.pe/AlumnoWS/modificarAlumnoResponse")]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.modificarAlumnoResponse> modificarAlumnoAsync(FrontTA.SisProgWS.modificarAlumnoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAlumno", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class insertarAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontTA.SisProgWS.alumno alumno;
        
        public insertarAlumnoRequest() {
        }
        
        public insertarAlumnoRequest(FrontTA.SisProgWS.alumno alumno) {
            this.alumno = alumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAlumnoResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class insertarAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAlumnoResponse() {
        }
        
        public insertarAlumnoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAlumnoPorId", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class eliminarAlumnoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        public eliminarAlumnoPorIdRequest() {
        }
        
        public eliminarAlumnoPorIdRequest(int idAlumno) {
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAlumnoPorIdResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class eliminarAlumnoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarAlumnoPorIdResponse() {
        }
        
        public eliminarAlumnoPorIdResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAlumnoPorId", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class obtenerAlumnoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        public obtenerAlumnoPorIdRequest() {
        }
        
        public obtenerAlumnoPorIdRequest(int idAlumno) {
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAlumnoPorIdResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class obtenerAlumnoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontTA.SisProgWS.alumno @return;
        
        public obtenerAlumnoPorIdResponse() {
        }
        
        public obtenerAlumnoPorIdResponse(FrontTA.SisProgWS.alumno @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnosTodos", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class listarAlumnosTodosRequest {
        
        public listarAlumnosTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnosTodosResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class listarAlumnosTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontTA.SisProgWS.alumno[] @return;
        
        public listarAlumnosTodosResponse() {
        }
        
        public listarAlumnosTodosResponse(FrontTA.SisProgWS.alumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAlumno", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class modificarAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontTA.SisProgWS.alumno alumno;
        
        public modificarAlumnoRequest() {
        }
        
        public modificarAlumnoRequest(FrontTA.SisProgWS.alumno alumno) {
            this.alumno = alumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAlumnoResponse", WrapperNamespace="http://alumno.services.sis.edu.pe/", IsWrapped=true)]
    public partial class modificarAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alumno.services.sis.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarAlumnoResponse() {
        }
        
        public modificarAlumnoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlumnoWSChannel : FrontTA.SisProgWS.AlumnoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumnoWSClient : System.ServiceModel.ClientBase<FrontTA.SisProgWS.AlumnoWS>, FrontTA.SisProgWS.AlumnoWS {
        
        public AlumnoWSClient() {
        }
        
        public AlumnoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumnoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.insertarAlumnoResponse FrontTA.SisProgWS.AlumnoWS.insertarAlumno(FrontTA.SisProgWS.insertarAlumnoRequest request) {
            return base.Channel.insertarAlumno(request);
        }
        
        public int insertarAlumno(FrontTA.SisProgWS.alumno alumno) {
            FrontTA.SisProgWS.insertarAlumnoRequest inValue = new FrontTA.SisProgWS.insertarAlumnoRequest();
            inValue.alumno = alumno;
            FrontTA.SisProgWS.insertarAlumnoResponse retVal = ((FrontTA.SisProgWS.AlumnoWS)(this)).insertarAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.insertarAlumnoResponse> FrontTA.SisProgWS.AlumnoWS.insertarAlumnoAsync(FrontTA.SisProgWS.insertarAlumnoRequest request) {
            return base.Channel.insertarAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.insertarAlumnoResponse> insertarAlumnoAsync(FrontTA.SisProgWS.alumno alumno) {
            FrontTA.SisProgWS.insertarAlumnoRequest inValue = new FrontTA.SisProgWS.insertarAlumnoRequest();
            inValue.alumno = alumno;
            return ((FrontTA.SisProgWS.AlumnoWS)(this)).insertarAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.eliminarAlumnoPorIdResponse FrontTA.SisProgWS.AlumnoWS.eliminarAlumnoPorId(FrontTA.SisProgWS.eliminarAlumnoPorIdRequest request) {
            return base.Channel.eliminarAlumnoPorId(request);
        }
        
        public int eliminarAlumnoPorId(int idAlumno) {
            FrontTA.SisProgWS.eliminarAlumnoPorIdRequest inValue = new FrontTA.SisProgWS.eliminarAlumnoPorIdRequest();
            inValue.idAlumno = idAlumno;
            FrontTA.SisProgWS.eliminarAlumnoPorIdResponse retVal = ((FrontTA.SisProgWS.AlumnoWS)(this)).eliminarAlumnoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.eliminarAlumnoPorIdResponse> FrontTA.SisProgWS.AlumnoWS.eliminarAlumnoPorIdAsync(FrontTA.SisProgWS.eliminarAlumnoPorIdRequest request) {
            return base.Channel.eliminarAlumnoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.eliminarAlumnoPorIdResponse> eliminarAlumnoPorIdAsync(int idAlumno) {
            FrontTA.SisProgWS.eliminarAlumnoPorIdRequest inValue = new FrontTA.SisProgWS.eliminarAlumnoPorIdRequest();
            inValue.idAlumno = idAlumno;
            return ((FrontTA.SisProgWS.AlumnoWS)(this)).eliminarAlumnoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.obtenerAlumnoPorIdResponse FrontTA.SisProgWS.AlumnoWS.obtenerAlumnoPorId(FrontTA.SisProgWS.obtenerAlumnoPorIdRequest request) {
            return base.Channel.obtenerAlumnoPorId(request);
        }
        
        public FrontTA.SisProgWS.alumno obtenerAlumnoPorId(int idAlumno) {
            FrontTA.SisProgWS.obtenerAlumnoPorIdRequest inValue = new FrontTA.SisProgWS.obtenerAlumnoPorIdRequest();
            inValue.idAlumno = idAlumno;
            FrontTA.SisProgWS.obtenerAlumnoPorIdResponse retVal = ((FrontTA.SisProgWS.AlumnoWS)(this)).obtenerAlumnoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.obtenerAlumnoPorIdResponse> FrontTA.SisProgWS.AlumnoWS.obtenerAlumnoPorIdAsync(FrontTA.SisProgWS.obtenerAlumnoPorIdRequest request) {
            return base.Channel.obtenerAlumnoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.obtenerAlumnoPorIdResponse> obtenerAlumnoPorIdAsync(int idAlumno) {
            FrontTA.SisProgWS.obtenerAlumnoPorIdRequest inValue = new FrontTA.SisProgWS.obtenerAlumnoPorIdRequest();
            inValue.idAlumno = idAlumno;
            return ((FrontTA.SisProgWS.AlumnoWS)(this)).obtenerAlumnoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.listarAlumnosTodosResponse FrontTA.SisProgWS.AlumnoWS.listarAlumnosTodos(FrontTA.SisProgWS.listarAlumnosTodosRequest request) {
            return base.Channel.listarAlumnosTodos(request);
        }
        
        public FrontTA.SisProgWS.alumno[] listarAlumnosTodos() {
            FrontTA.SisProgWS.listarAlumnosTodosRequest inValue = new FrontTA.SisProgWS.listarAlumnosTodosRequest();
            FrontTA.SisProgWS.listarAlumnosTodosResponse retVal = ((FrontTA.SisProgWS.AlumnoWS)(this)).listarAlumnosTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.listarAlumnosTodosResponse> FrontTA.SisProgWS.AlumnoWS.listarAlumnosTodosAsync(FrontTA.SisProgWS.listarAlumnosTodosRequest request) {
            return base.Channel.listarAlumnosTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.listarAlumnosTodosResponse> listarAlumnosTodosAsync() {
            FrontTA.SisProgWS.listarAlumnosTodosRequest inValue = new FrontTA.SisProgWS.listarAlumnosTodosRequest();
            return ((FrontTA.SisProgWS.AlumnoWS)(this)).listarAlumnosTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontTA.SisProgWS.modificarAlumnoResponse FrontTA.SisProgWS.AlumnoWS.modificarAlumno(FrontTA.SisProgWS.modificarAlumnoRequest request) {
            return base.Channel.modificarAlumno(request);
        }
        
        public int modificarAlumno(FrontTA.SisProgWS.alumno alumno) {
            FrontTA.SisProgWS.modificarAlumnoRequest inValue = new FrontTA.SisProgWS.modificarAlumnoRequest();
            inValue.alumno = alumno;
            FrontTA.SisProgWS.modificarAlumnoResponse retVal = ((FrontTA.SisProgWS.AlumnoWS)(this)).modificarAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontTA.SisProgWS.modificarAlumnoResponse> FrontTA.SisProgWS.AlumnoWS.modificarAlumnoAsync(FrontTA.SisProgWS.modificarAlumnoRequest request) {
            return base.Channel.modificarAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontTA.SisProgWS.modificarAlumnoResponse> modificarAlumnoAsync(FrontTA.SisProgWS.alumno alumno) {
            FrontTA.SisProgWS.modificarAlumnoRequest inValue = new FrontTA.SisProgWS.modificarAlumnoRequest();
            inValue.alumno = alumno;
            return ((FrontTA.SisProgWS.AlumnoWS)(this)).modificarAlumnoAsync(inValue);
        }
    }
}
